- name: Build Debug APK
  run: |
    echo "=== Environment ==="
    echo "JAVA_HOME: $JAVA_HOME"
    echo "ANDROID_HOME: $ANDROID_HOME"
    
    echo "=== Java version ==="
    java -version
    
    echo "=== Building APK with stacktrace ==="
    ./gradlew assembleDebug --no-daemon --console=plain --stacktrace --info
