name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      env:
        MATTERMOST_SERVER_URL: ${{ secrets.MATTERMOST_SERVER_URL }}
        MATTERMOST_CHANNEL_ID: ${{ secrets.MATTERMOST_CHANNEL_ID }}
        MATTERMOST_LOGIN: ${{ secrets.MATTERMOST_LOGIN }}
        MATTERMOST_TOKEN: ${{ secrets.MATTERMOST_TOKEN }}
        SERVER_ENDPOINT_URL: ${{ secrets.SERVER_ENDPOINT_URL }}
        DEFAULT_SMS_NUMBER: ${{ secrets.DEFAULT_SMS_NUMBER }}
        KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        # Create keystore from secret
        echo "$KEYSTORE_FILE" | base64 -d > app/keystore.jks
        
        # Create local.properties for build
        echo "storeFile=keystore.jks" > local.properties
        echo "storePassword=$KEYSTORE_PASSWORD" >> local.properties
        echo "keyAlias=$KEY_ALIAS" >> local.properties
        echo "keyPassword=$KEY_PASSWORD" >> local.properties
        
        ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 7

    - name: Upload mapping file
      uses: actions/upload-artifact@v4
      with:
        name: mapping-file
        path: app/build/outputs/mapping/release/mapping.txt
        retention-days: 7

    - name: Show build info
      run: |
        echo "Build completed successfully!"
        echo "APK location: app/build/outputs/apk/release/app-release.apk"
        echo "APK size: $(du -h app/build/outputs/apk/release/app-release.apk | cut -f1)"
