name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Gradle
      run: |
        sudo apt-get update
        sudo apt-get install -y gradle
        gradle --version

    - name: Set up environment
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV

    - name: Build with Gradle
      run: |
        gradle wrapper --version
        gradle assembleDebug --no-daemon --console=plain

    - name: Upload APK Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 7

    - name: Show build results
      if: always()
      run: |
        echo "=== BUILD RESULTS ==="
        find app/build -name "*.apk" -exec ls -la {} \; 2>/dev/null || echo "No APK files found"
